### PR TITLE
Angle bracket escaping issue

### LINKED ISSUE #30: BrowsableAPIRenderer does not escape angle brackets
If you have an Flask-API view that returns JSON containing angle brackets, like this...

     {"test": "I <3 Python"}

The angle bracket is not encoded as a <kbd>&amp;lt;</kbd> (or <kbd>&amp;gt;</kbd> in the case of a greater than angle bracket) entity in the HTML source code.

(I know from the README that the project isn't being maintained, but filing it for future reference. :smiley:)

### PR DESCRIPTION
**Pull request by tommorris**
Fixes #30.

### CODE REVIEW

**Comment by tomchristie** [comment]
@tommorris Are you interested in maintainership, given the current status of this project?

**Comment by tommorris** [comment]
@tomchristie Possibly. I can't guarantee to put much time into it, but I can certainly give it a try.

**Comment by jacebrowning** [comment]
@tommorris Can you add a unit test for this change? Another method in `test_renderers.RendererTests` that converts ` {"test": "I <3 Python"}` to JSON should do the trick.

**Comment by tommorris** [comment]
@jacebrowning: okay, added some tests and the CI builds pass on both python2 and python3.

**Pull request merged**
