### PR TITLE
Release v0.6.3

### PR DESCRIPTION
**Pull request by jacebrowning**
Also cleaned up some spelling/formatting issues for release.

### CODE REVIEW

**Comment by jacebrowning** [comment]
@tomchristie A decent number of fixes have been merged since `0.6.2`, so I think it's time for a bugfix release. Did I make all the necessary version/documentation changes? What needs to happen for you to upload this?

**Comment by tomchristie** [comment]
@jacebrowning If you make sure you have a pypi username and then let me know what it is I'll give you the relevant permissions! :)

**Comment by jacebrowning** [comment]
@tomchristie My PyPI username is the same as GitHub!

**Comment by tomchristie** [comment]
@jacebrowning Added. You should now be able to run `setup.py publish`.
Let me know if you also need any info about pushing the docs?

**Comment by jacebrowning** [comment]
@tomchristie Assuming the docs should be published after every version, I do need some instructions for that.

**Comment by jacebrowning** [comment]
@tomchristie Figured it out:

```
$ mkdocs build  # generate site
$ mkdocs serve  # do it live

$ mkdocs gh-deploy  # ship it!
```

`mkdocs` looks pretty sweet, I'll have to use it more!

**Comment by tomchristie** [comment]
Wonderful stuff - nice work @jacebrowning!

> `mkdocs` looks pretty sweet, I'll have to use it more!

Yeah - also it's happily under @d0ugal's stewardship now and doing very, very nicely!

**Comment by d0ugal** [comment]
Happy to help with any general questions there :) I just released 0.13 which is a huge release for MkDocs.

**Comment by d0ugal** [comment]
Oh, I see you already have 0.13 :) Congrats on being one of our first users to use MkDocs search!

**Comment by tomchristie** [comment]
@d0ugal Just tried it on http://www.flaskapi.org/ - looks kickass! Looking forward to seeing that in REST framework :)

**Pull request merged**
